new_user: cicd
new_user_ssh_pub: "{{ lookup('file', '{{ playbook_dir }}/credentials/ssh/cicd.pub') }}"
folders_to_change_owner:
  - /data/apps/
  - /data/tests/
docker_users:
  - "{{ ansible_user }}"
  - "{{ new_user }}"
docker_compose_version: "1.29.2"