---

- name: Create user {{ new_user }}
  user:
    name: '{{ new_user }}'
    state: present
    shell: /bin/bash
    create_home: yes
    home: /home/{{ new_user }}


- name: Add ssh public key in authorized key
  authorized_key:
    user: '{{ new_user }}'
    state: present
    key: '{{ new_user_ssh_pub }}'


- name: Change folders ownership
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    owner: "{{ new_user }}"
    group: "{{ new_user }}"
  loop: "{{ folders_to_change_owner|default([]) }}"


- name: Add '{{ ansible_user }}' user to '{{ new_user }}' group
  user:
    name: '{{ ansible_user }}'
    groups: '{{ new_user }}'
    append: yes
